import { Lang } from "./types";

export const ROUTES = [
  "Yangiyer → Toshkent", "Toshkent → Yangiyer",
  "Toshkent → Guliston", "Guliston → Toshkent",
  "Yangiyer → Guliston", "Guliston → Yangiyer",
];

export const CONFIG = {
  ORDER_EXPIRY_MINUTES: 15,
  AUTO_RETRY_ENABLED: true,
  MAX_AUTO_RETRIES: 3,
  BREAK_DURATIONS: [30, 60, 120, 180],
  LEADERBOARD_TOP: 10,
  EARNINGS_PER_PAGE: 5,
  CLEANUP_INTERVAL_MS: 30 * 60 * 1000,
  SURGE_THRESHOLD: 5,
  WAIT_TIME_BASE_MINUTES: 5,
  MAX_ORDER_AGE_HOURS: 24,
  BROADCAST_CHUNK_SIZE: 30,
  BROADCAST_DELAY_MS: 1000,
};

export const TEXTS: Record<string, Record<Lang, string>> = {
  welcome:        { uz: "Assalomu alaykum",         ru: "Добро пожаловать" },
  chooseRole:     { uz: "Quyidagilardan birini tanlang:", ru: "Выберите один из вариантов:" },
  btnDriver:      { uz: "🚗 Haydovchi",              ru: "🚗 Водитель" },
  btnPassenger:   { uz: "🧑 Yo'lovchi",              ru: "🧑 Пассажир" },
  btnAnnounce:    { uz: "📢 E'lonlar",               ru: "📢 Объявления" },
  btnParcel:      { uz: "📦 Posilka",                ru: "📦 Посылка" },
  btnAdmin:       { uz: "👨‍💼 Admin panel",           ru: "👨‍💼 Админ панель" },
  btnHistory:     { uz: "📜 Tarixim",                ru: "📜 История" },
  btnCancel:      { uz: "❌ Bekor qilish",           ru: "❌ Отмена" },
  btnSharePhone:  { uz: "📱 Telefon ulashish",       ru: "📱 Поделиться номером" },
  enterName:      { uz: "Ismingizni kiriting:",      ru: "Введите ваше имя:" },
  enterPhone:     { uz: "📱 Telefon raqamingizni ulashing:", ru: "📱 Поделитесь номером телефона:" },
  enterCarModel:  { uz: "🚗 Mashina modelini kiriting (masalan: Cobalt):", ru: "🚗 Введите модель авто (например: Cobalt):" },
  enterCarNum:    { uz: "🔢 Mashina raqamini kiriting (01A123BC):", ru: "🔢 Введите номер авто (01A123BC):" },
  chooseRoute:    { uz: "📍 Yo'nalishni tanlang:", ru: "📍 Выберите маршрут:" },
  enterSeats:     { uz: "💺 Nechta bo'sh o'rindiq? (1-6):", ru: "💺 Сколько свободных мест? (1-6):" },
  enterSeatsP:    { uz: "💺 Nechta o'rindiq kerak? (1-4):", ru: "💺 Сколько мест нужно? (1-4):" },
  enterTime:      { uz: "🕐 Jo'nash vaqti (masalan: 08:30):", ru: "🕐 Время отправления (например: 08:30):" },
  enterPrice:     { uz: "💰 Narxni kiriting (so'mda):", ru: "💰 Введите цену (в сумах):" },
  mainMenu:       { uz: "Asosiy menyu:", ru: "Главное меню:" },
  invalidSeats:   { uz: "Iltimos, to'g'ri son kiriting:", ru: "Пожалуйста, введите правильное число:" },
  invalidPrice:   { uz: "Iltimos, to'g'ri narx kiriting:", ru: "Пожалуйста, введите корректную цену:" },
  orderSent:      { uz: "✅ Buyurtmangiz qabul qilindi! Haydovchi topilganda xabar beramiz. 🔔", ru: "✅ Ваш заказ принят! Уведомим вас, когда найдём водителя. 🔔" },
  noDrivers:      { uz: "😔 Hozircha bu yo'nalishda haydovchi topilmadi.", ru: "😔 Пока нет водителей на этот маршрут." },
  driverFound:    { uz: "🎉 Haydovchi topildi!", ru: "🎉 Водитель найден!" },
  rateTrip:       { uz: "⭐ Sayohatingiz qanday bo'ldi? Haydovchiga baho bering:", ru: "⭐ Как прошла поездка? Оцените водителя:" },
  thankRating:    { uz: "Rahmat! Bahongiz qabul qilindi.", ru: "Спасибо! Ваша оценка принята." },
  chooseCompRoute:{ uz: "Shikoyat qaysi yo'nalishda bo'ldi? Yo'nalishni tanlang:", ru: "По какому маршруту жалоба? Выберите маршрут:" },
  enterComplaint: { uz: "📝 Shikoyatingizni yozing:", ru: "📝 Напишите вашу жалобу:" },
  complaintSent:  { uz: "✅ Shikoyatingiz adminga yuborildi. Rahmat!", ru: "✅ Жалоба отправлена администратору. Спасибо!" },
  parcelRoute:    { uz: "📦 Posilka yo'nalishini tanlang:", ru: "📦 Выберите маршрут посылки:" },
  parcelDesc:     { uz: "📦 Posilkani tasvirlab bering (og'irligi, nomi):", ru: "📦 Опишите посылку (вес, название):" },
  parcelSent:     { uz: "✅ Posilka so'rovi yuborildi! Haydovchi topilganda xabar beramiz.", ru: "✅ Запрос на посылку отправлен! Уведомим когда найдём водителя." },
  newParcel:      { uz: "📦 Yangi posilka so'rovi!", ru: "📦 Новый запрос на посылку!" },
  msgRelay:       { uz: "💬 Xabaringizni yuboring (haydovchi ko'radi):", ru: "💬 Напишите сообщение (водитель увидит):" },
  msgSent:        { uz: "✅ Xabaringiz yuborildi.", ru: "✅ Сообщение отправлено." },
  msgFrom:        { uz: "💬 Yo'lovchidan xabar:", ru: "💬 Сообщение от пассажира:" },
  msgFromDriver:  { uz: "💬 Haydovchidan xabar:", ru: "💬 Сообщение от водителя:" },
  noHistory:      { uz: "Hozircha sayohat tarixi yo'q.", ru: "История поездок пока пуста." },
  adminPending:   { uz: "⏳ Admin tasdiqlaganidan so'ng buyurtmalar olasiz.", ru: "⏳ После подтверждения администратора получите заказы." },
  approved:       { uz: "🎉 Siz tasdiqlanding! Buyurtmalar olishingiz mumkin!", ru: "🎉 Вы подтверждены! Можете получать заказы!" },
  blocked:        { uz: "❌ Akkauntingiz bloklandi. Admin bilan bog'laning.", ru: "❌ Ваш аккаунт заблокирован. Свяжитесь с администратором." },
  unblocked:      { uz: "✅ Akkauntingiz blokdan chiqarildi!", ru: "✅ Ваш аккаунт разблокирован!" },
  reminder:       { uz: "🔔 Eslatma! 30 daqiqadan so'ng sayohatingiz boshlanadi.", ru: "🔔 Напоминание! Через 30 минут начнётся ваша поездка." },
  chooseLanguage: { uz: "Tilni tanlang / Выберите язык:", ru: "Tilni tanlang / Выберите язык:" },
  announce:       { uz: "📢 Haydovchilar e'lonlari:", ru: "📢 Объявления водителей:" },
  noAnnounce:     { uz: "Hozircha e'lonlar yo'q.", ru: "Пока нет объявлений." },
  announceRoute:  { uz: "📍 Qaysi yo'nalish bo'yicha ko'rmoqchisiz?", ru: "📍 По какому маршруту хотите посмотреть?" },
  announceAll:    { uz: "🌐 Barcha yo'nalishlar", ru: "🌐 Все маршруты" },
  noDriversRoute: { uz: "😔 Bu yo'nalishda online haydovchi yo'q.", ru: "😔 На этом маршруте нет онлайн водителей." },
  btnOrderDriver: { uz: "🚕 Buyurtma berish", ru: "🚕 Заказать" },
  btnCallDriver:  { uz: "📞 Telefon ko'rish", ru: "📞 Показать телефон" },
  btnBackRoutes:  { uz: "◀️ Yo'nalishlar", ru: "◀️ Маршруты" },
  btnComplaint:   { uz: "🚫 Shikoyat",             ru: "🚫 Жалоба" },
  btnMsg:         { uz: "💬 Xabar yuborish",        ru: "💬 Отправить сообщение" },
  btnOnline:      { uz: "🟢 Online (faol)",         ru: "🟢 Онлайн (активен)" },
  btnOffline:     { uz: "🔴 Offline (dam olish)",   ru: "🔴 Оффлайн (отдыхаю)" },
  btnMyStatus:    { uz: "📡 Mening holatim",        ru: "📡 Мой статус" },
  onlineSet:      { uz: "🟢 Siz ONLINE! Buyurtmalar kela boshlaydi.", ru: "🟢 Вы ОНЛАЙН! Заказы начнут поступать." },
  offlineSet:     { uz: "🔴 Siz OFFLINE. Buyurtmalar kelmaydi.", ru: "🔴 Вы ОФФЛАЙН. Заказы не поступают." },
  onlineDrivers:  { uz: "🟢 Online haydovchilar:", ru: "🟢 Водители онлайн:" },
  offlineDrivers: { uz: "🔴 Offline haydovchilar:", ru: "🔴 Водители оффлайн:" },
  noOnlineDrivers:{ uz: "😔 Hozircha online haydovchi yo'q. Keyinroq urinib ko'ring.", ru: "😔 Сейчас нет онлайн водителей. Попробуйте позже." },
  btnSOS:         { uz: "🆘 SOS - Xavfsizlik",       ru: "🆘 SOS - Безопасность" },
  sosConfirm:     { uz: "🆘 SOS xabar yuborildi! Admin va haydovchi darhol xabardor qilindi!", ru: "🆘 SOS отправлен! Администратор и водитель немедленно уведомлены!" },
  sosAlert:       { uz: "🚨 XAVFLI HOLAT - SOS SIGNAL!", ru: "🚨 ОПАСНАЯ СИТУАЦИЯ - SOS СИГНАЛ!" },
  sosMenu:        { uz: "🆘 SOS menyusi. Xavfli holatda foydalaning:", ru: "🆘 SOS меню. Используйте в опасной ситуации:" },
  btnSosSend:     { uz: "🚨 XAVFDA EKANMAN - SOS YUBORISH", ru: "🚨 Я В ОПАСНОСТИ - ОТПРАВИТЬ SOS" },
  btnSosCancel:   { uz: "✅ Xavfsizman - Orqaga", ru: "✅ Я в безопасности - Назад" },
  blacklisted:    { uz: "🚫 Siz tizimdan chiqarilgansiz. Muammo uchun: @admin", ru: "🚫 Вы заблокированы. По вопросам: @admin" },
  btnBlacklist:   { uz: "🚫 Blacklist",              ru: "🚫 Чёрный список" },
  noBlacklist:    { uz: "Blacklist bo'sh.", ru: "Чёрный список пуст." },
  btnQuickOrder:  { uz: "⚡ Tez buyurtma",           ru: "⚡ Быстрый заказ" },
  noLastOrder:    { uz: "Avvalgi buyurtma yo'q.", ru: "Предыдущего заказа нет." },
  quickOrderInfo: { uz: "⚡ Oxirgi buyurtmangiz:", ru: "⚡ Ваш последний заказ:" },
  quickOrderDone: { uz: "✅ Tez buyurtma yuborildi!", ru: "✅ Быстрый заказ отправлен!" },
  btnShareLoc:    { uz: "📍 Joylashuvni ulashish (ixtiyoriy)", ru: "📍 Поделиться местоположением (необязательно)" },
  btnSkipLoc:     { uz: "⏭ O'tkazib yuborish",      ru: "⏭ Пропустить" },
  locShared:      { uz: "📍 Joylashuvingiz haydovchiga yuborildi!", ru: "📍 Ваше местоположение отправлено водителю!" },
  locFromPass:    { uz: "📍 Yo'lovchi joylashuvi:", ru: "📍 Местоположение пассажира:" },
  btnBroadcast:   { uz: "📢 Hammaga xabar",          ru: "📢 Сообщение всем" },
  broadcastPrompt:{ uz: "📢 Barcha foydalanuvchilarga yuboriladigan xabarni yozing:", ru: "📢 Напишите сообщение для всех пользователей:" },
  broadcastSent:  { uz: "✅ Xabar yuborildi: {count} nafar.", ru: "✅ Сообщение отправлено: {count} чел." },
  btnStats:       { uz: "📊 Statistika",             ru: "📊 Статистика" },
  btnMyOrders:    { uz: "📋 Faol buyurtmalarim",     ru: "📋 Мои активные заказы" },
  noActiveOrders: { uz: "📋 Faol buyurtma yo'q.",    ru: "📋 Нет активных заказов." },
  btnMyStats:     { uz: "📊 Mening statistikam",     ru: "📊 Моя статистика" },
  btnTomorrow:    { uz: "📅 Ertangi bron",           ru: "📅 Бронь на завтра" },
  tomorrowInfo:   { uz: "📅 Ertangi bron — ertaga jo'nash uchun joy band qiling:", ru: "📅 Бронь на завтра — забронируйте место на завтра:" },
  tomorrowDone:   { uz: "✅ Ertangi bron qabul qilindi! Haydovchi topilganda xabar beramiz. 🔔", ru: "✅ Бронь на завтра принята! Уведомим вас, когда найдём водителя. 🔔" },
  btnAdminReply:  { uz: "💬 Foydalanuvchiga javob", ru: "💬 Ответить пользователю" },
  adminReplyWho:  { uz: "👤 Kimga javob yozmoqchisiz? Foydalanuvchini tanlang:", ru: "👤 Кому хотите ответить? Выберите пользователя:" },
  adminReplyType: { uz: "✏️ Xabaringizni yozing (foydalanuvchi ko'radi):", ru: "✏️ Напишите сообщение (пользователь увидит):" },
  adminReplySent: { uz: "✅ Xabar yuborildi!", ru: "✅ Сообщение отправлено!" },
  msgFromAdmin:   { uz: "📩 Admin xabari:", ru: "📩 Сообщение от администратора:" },
  btnEdit:        { uz: "🔄 Ma'lumotlarni tahrirlash", ru: "🔄 Редактировать данные" },
  editWhat:       { uz: "Nimani o'zgartirmoqchisiz?", ru: "Что хотите изменить?" },
  editDone:       { uz: "✅ Ma'lumot yangilandi!", ru: "✅ Данные обновлены!" },
  editPriceBtn:   { uz: "💰 Narx", ru: "💰 Цена" },
  editTimeBtn:    { uz: "🕐 Vaqt", ru: "🕐 Время" },
  editSeatsBtn:   { uz: "💺 O'rindiq", ru: "💺 Места" },
  editRouteBtn:   { uz: "📍 Yo'nalish", ru: "📍 Маршрут" },
  rejectReason:   { uz: "❓ Rad etish sababini yozing (yo'lovchiga yuboriladi):", ru: "❓ Напишите причину отказа (пассажир увидит):" },
  rejectedReason: { uz: "😔 Haydovchi buyurtmangizni rad etdi.\n📝 Sabab:", ru: "😔 Водитель отклонил ваш заказ.\n📝 Причина:" },
  reviewPrompt:   { uz: "💬 Izoh qoldiring (ixtiyoriy). O'tkazib yuborish uchun — /skip:", ru: "💬 Оставьте отзыв (необязательно). Пропустить — /skip:" },
  reviewSaved:    { uz: "✅ Izohingiz qabul qilindi. Rahmat!", ru: "✅ Отзыв сохранён. Спасибо!" },
  btnReminder:    { uz: "🔔 Eslatma sozlamasi", ru: "🔔 Настройка напоминания" },
  reminderOnMsg:  { uz: "🔔 Eslatma YOQILDI — jo'nashdan 30 daqiqa oldin xabar olasiz.", ru: "🔔 Напоминание ВКЛЮЧЕНО — получите уведомление за 30 минут." },
  reminderOffMsg: { uz: "🔕 Eslatma O'CHIRILDI — endi xabar kelmaydi.", ru: "🔕 Напоминание ОТКЛЮЧЕНО — уведомлений не будет." },
  btnHelp:        { uz: "❓ Yordam", ru: "❓ Помощь" },
  helpText:       { uz: `❓ <b>Bot haqida yordam</b>\n\n🚗 <b>Haydovchi</b> — ro'yxatdan o'ting, tasdiqlanganingizdan so'ng buyurtmalar olasiz.\n🟢 Online tugmasini bossangiz — buyurtmalar kela boshlaydi.\n\n🧑 <b>Yo'lovchi</b> — yo'nalishni tanlang, ma'lumotlaringizni kiriting, haydovchi topilganda xabar keladi.\n\n📅 <b>Ertangi bron</b> — ertaga uchun joy oldindan band qilish.\n\n📋 <b>Faol buyurtmalarim</b> — buyurtmalaringizni ko'ring, bekor qiling.\n\n📢 <b>E'lonlar</b> — online haydovchilarni ko'ring va bevosita buyurtma bering.\n\n📦 <b>Posilka</b> — tovar yoki hujjat yuborish.\n\n🆘 <b>SOS</b> — xavfli holatda bosing — admin va haydovchi darhol xabardor bo'ladi.\n\n🤝 <b>Referal</b> — do'stlarni taklif qiling!`, ru: `❓ <b>Помощь по боту</b>\n\n🚗 <b>Водитель</b> — зарегистрируйтесь, после подтверждения получайте заказы.\n🟢 Нажмите Онлайн — заказы начнут поступать.\n\n🧑 <b>Пассажир</b> — выберите маршрут, введите данные, получите уведомление когда найдётся водитель.\n\n📅 <b>Бронь на завтра</b> — забронируйте место заранее.\n\n📋 <b>Мои активные заказы</b> — просматривайте и отменяйте заказы.\n\n📢 <b>Объявления</b> — смотрите онлайн водителей и заказывайте напрямую.\n\n📦 <b>Посылка</b> — отправить товар или документы.\n\n🆘 <b>SOS</b> — в опасной ситуации — нажмите, администратор и водитель сразу узнают.\n\n🤝 <b>Реферал</b> — приглашайте друзей!` },
  btnReferral:    { uz: "🤝 Do'stni taklif qil", ru: "🤝 Пригласить друга" },
  referralText:   { uz: "🤝 <b>Referal tizimi</b>\n\nDo'stlaringizni taklif qiling!\nSizning shaxsiy linkingiz:", ru: "🤝 <b>Реферальная система</b>\n\nПриглашайте друзей!\nВаша персональная ссылка:" },
  referralCount:  { uz: "👥 Siz taklif qilganlar:", ru: "👥 Вы пригласили:" },
  adminExport:    { uz: "📤 Haydovchilar eksporti", ru: "📤 Экспорт водителей" },
  adminTomorrow:  { uz: "📅 Ertangi bronlar", ru: "📅 Брони на завтра" },
  btnSchedule:    { uz: "📅 Jadval", ru: "📅 Расписание" },
  btnEarnings:    { uz: "💵 Daromadlar", ru: "💵 Доходы" },
  btnAnalytics:   { uz: "📊 Tahlil", ru: "📊 Аналитика" },
  btnBreak:       { uz: "⏸️ Tanaffus", ru: "⏸️ Перерыв" },
  btnLeaderboard: { uz: "🏆 Yetakchilar", ru: "🏆 Лидеры" },
  scheduleTitle:  { uz: "📅 Haftalik jadval", ru: "📅 Недельное расписание" },
  scheduleSet:    { uz: "✅ Jadval saqlandi!", ru: "✅ Расписание сохранено!" },
  schedulePrompt: { uz: "Faol kunlarni tanlang (1-7):\n1-Dushanba, 2-Seshanba...\nMasalan: 1,2,3,4,5", ru: "Выберите активные дни (1-7):\n1-Пн, 2-Вт...\nНапример: 1,2,3,4,5" },
  scheduleTime:   { uz: "Ish vaqtini kiriting (masalan: 08:00-20:00):", ru: "Введите рабочее время (например: 08:00-20:00):" },
  earningsTitle:  { uz: "💵 Daromadlar", ru: "💵 Доходы" },
  earningsEmpty:  { uz: "Hozircha daromad yo'q.", ru: "Пока нет доходов." },
  earningsDaily:  { uz: "📅 Bugun", ru: "📅 Сегодня" },
  earningsWeekly: { uz: "📅 Bu hafta", ru: "📅 Эта неделя" },
  earningsMonthly:{ uz: "📅 Bu oy", ru: "📅 Этот месяц" },
  analyticsTitle: { uz: "📊 Reyting tahlili", ru: "📊 Анализ рейтинга" },
  breakPrompt:    { uz: "Tanaffuz muddatini tanlang:", ru: "Выберите длительность перерыва:" },
  breakSet:       { uz: "⏸️ Tanaffus rejimi yoqildi. {min} daqiqadan so'ng avtomatik online bo'lasiz.", ru: "⏸️ Режим перерыва включён. Через {min} минут вы автоматически станете онлайн." },
  breakDone:      { uz: "✅ Tanaffus tugadi! Online rejimga qaytdingiz.", ru: "✅ Перерыв окончен! Вы снова онлайн." },
  leaderboardTitle:{ uz: "🏆 Eng yaxshi haydovchilar", ru: "🏆 Лучшие водители" },
  leaderboardPos: { uz: "Sizning o'rningiz", ru: "Ваша позиция" },
  btnFavorites:   { uz: "⭐ Sevimli haydovchilar", ru: "⭐ Любимые водители" },
  btnSavedPlaces: { uz: "🏠 Saqlangan manzillar", ru: "🏠 Сохранённые адреса" },
  btnBookForOther:{ uz: "👤 Boshqa uchun buyurtma", ru: "👤 Заказ для другого" },
  btnOrderNotes:  { uz: "📝 Buyurtma izohi", ru: "📝 Примечание к заказу" },
  btnEmergency:   { uz: "🆘 Favqulodda kontakt", ru: "🆘 Экстренный контакт" },
  btnShareTrip:   { uz: "📤 Sayohatni ulashish", ru: "📤 Поделиться поездкой" },
  btnQuickMsgs:   { uz: "💬 Tez xabarlar", ru: "💬 Быстрые сообщения" },
  favoritesTitle: { uz: "⭐ Sevimli haydovchilar", ru: "⭐ Любимые водители" },
  noFavorites:    { uz: "Hozircha sevimli haydovchi yo'q.", ru: "Пока нет любимых водителей." },
  favoriteAdded:  { uz: "⭐ Haydovchi sevimlilarga qo'shildi!", ru: "⭐ Водитель добавлен в избранное!" },
  savedPlacesTitle:{ uz: "🏠 Saqlangan manzillar", ru: "🏠 Сохранённые адреса" },
  noSavedPlaces:  { uz: "Hozircha saqlangan manzil yo'q.", ru: "Пока нет сохранённых адресов." },
  addressAdded:   { uz: "✅ Manzil saqlandi!", ru: "✅ Адрес сохранён!" },
  bookForOtherTitle:{ uz: "👤 Boshqa uchun buyurtma", ru: "👤 Заказ для другого" },
  bookForOtherName:{ uz: "Yo'lovchi ismini kiriting:", ru: "Введите имя пассажира:" },
  bookForOtherPhone:{ uz: "Yo'lovchi telefonini kiriting:", ru: "Введите телефон пассажира:" },
  emergencyTitle: { uz: "🆘 Favqulodda kontakt", ru: "🆘 Экстренный kontakt" },
  emergencySet:   { uz: "✅ Favqulodda kontakt saqlandi!", ru: "✅ Экстренный контакт сохранён!" },
  emergencyPrompt:{ uz: "Kontakt ismini kiriting:", ru: "Введите имя контакта:" },
  orderNotesPrompt:{ uz: "📝 Haydovchiga izoh (yuk, bolalar, hayvonlar):", ru: "📝 Примечание водителю (багаж, дети, животные):" },
  shareTripText:  { uz: "📤 Sayohat ma'lumotlari:", ru: "📤 Данные поездки:" },
  quickMsgTitle:  { uz: "💬 Tez xabar tanlang:", ru: "💬 Выберите быстрое сообщение:" },
  waitTimeEst:    { uz: "⏱️ Taxminiy kutish vaqti: {time} daqiqa", ru: "⏱️ Примерное время ожидания: {time} мин" },
  orderExpired:   { uz: "⏳ Buyurtma muddati tugadi. Qayta urinib ko'ring.", ru: "⏳ Срок заказа истёк. Попробуйте снова." },
  autoRetryOn:    { uz: "🔄 Avto-qayta qidiruv YOQILDI", ru: "🔄 Авто-поиск ВКЛЮЧЁН" },
  autoRetryOff:   { uz: "🔄 Avto-qayta qidiruv O'CHIRILDI", ru: "🔄 Авто-поиск ОТКЛЮЧЁН" },
  surgeNotice:    { uz: "⚡ Bu yo'nalishda talab yuqori! Narx oshishi mumkin.", ru: "⚡ На этом маршруте высокий спрос! Цена может вырасти." },
  btnRouteAnalytics:{ uz: "📊 Yo'nalish analitikasi", ru: "📊 Аналитика маршрутов" },
  btnLeaderboardAdmin:{ uz: "🏆 Yetakchilar ro'yxati", ru: "🏆 Список лидеров" },
  btnScheduledBroadcast:{ uz: "📅 Rejalashtirilgan xabar", ru: "📅 Запланированное сообщение" },
  btnMassApprove: { uz: "✅ Mass tasdiqlash", ru: "✅ Массовое подтверждение" },
  btnCleanup:     { uz: "🧹 Tozalash", ru: "🧹 Очистка" },
  routeAnalyticsTitle:{ uz: "📊 Yo'nalish analitikasi", ru: "📊 Аналитика маршрутов" },
  massApproveDone:{ uz: "✅ {count} ta haydovchi tasdiqlandi!", ru: "✅ Подтверждено {count} водителей!" },
  cleanupDone:    { uz: "🧹 {count} ta eski ma'lumot tozalandi.", ru: "🧹 Очищено {count} старых записей." },
  scheduledSet:   { uz: "✅ Xabar rejalashtirildi!", ru: "✅ Сообщение запланировано!" },
};
